### ISSUE TITLE
Wheel contains mystery file in versions 2.11.0 & 2.11.1

### ISSUE THREAD

**Issue by harkylton** [SAML-Toolkits/python-saml#294]
The wheel distributed on pypi for versions 2.11.0 & 2.11.1 contains a `lxml.py` file in the `onelogin/saml2` package, breaking any imports from `lxml` in the package. This file is not present in the source distributions for the same versions. 

For us, this manifested as `ImportError: cannot import name etree` in `onelogin/saml2/utils.py` when trying to import any modules from the `python-saml` package after upgrading from `2.8.0` to `2.11.1`

Can you republish these versions?

**Comment by pcustic** [comment]
+1

Found the same issue. I needed to fix version to 2.10.0 in the requirements file to be able to get it to work properly.

**Comment by pitbulk** [comment]
I will do a new release fixing such issue.

**Comment by pitbulk** [comment]
2.12.0 was released
