### ISSUE TITLE
providing container name for IDP and SP

### ISSUE THREAD

**Issue by indiVar0508** [SAML-Toolkits/python-saml#314]
Hi 

I was setting up IDP provider locally through a docker container locally, this container is part of bridge network of (SP)application container, but when i try to saml setting ACS and IDP SSO URL with container name, i get invalid name error

I was going through code and found that this regex checks for host name to be either `localhost` or `ipv4` or `ipv6`, 
https://github.com/SAML-Toolkits/python-saml/blob/master/src/onelogin/saml2/settings.py#L33

but in a docker setup this can also container name so wanted to know if this was intentional or should be considered a minor issue,

for now i exposed IDP provider port to host and connecting to IDP via host ( by giving localhost ) which makes the validate_url check pass.

Thanks

**Comment by pitbulk** [comment]
I guess I did not consider containers when I added the validation.

But as you already did is not hard to run the Container with a custom hostname.
