### ISSUE TITLE
Error While process_response()

### ISSUE THREAD

**Issue by MehtaKajol** [SAML-Toolkits/python-saml#316]
I am using
req = prepare_lambda_request(event)
auth = init_saml_auth(req)
auth.process_response()

I get the following error: 
{'errorMessage': 'Invalid base64-encoded string: number of data      
characters (10617) cannot be 1 more than a multiple of 4',           
'errorType': 'Error', 'requestId':                                   
'1a20844e-2751-4761-8919-105bba04b476', 'stackTrace': ['  File       
"/var/task/app.py", line 91, in lambda_handler\n    return acs(event,
context)\n', '  File "/var/task/app.py", line 64, in acs\n           
auth.process_response()\n', '  File                                  
"/var/task/onelogin/saml2/auth.py", line 128, in process_response\n  
response = self.response_class(self._settings,                       
self._request_data[\'post_data\'][\'SAMLResponse\'])\n', '  File     
"/var/task/onelogin/saml2/response.py", line 36, in __init__\n       
self.response = OneLogin_Saml2_Utils.b64decode(response)\n', '  File 
"/var/task/onelogin/saml2/utils.py", line 98, in b64decode\n         
return base64.b64decode(data)\n', '  File                            
"/var/lang/lib/python3.10/base64.py", line 87, in b64decode\n        
return binascii.a2b_base64(s)\n']}

Can someone please guide me? Also I want to extract attributes so I can use them.

**Comment by pitbulk** [comment]
I see you were able to pass this step by using python3-saml:
https://github.com/SAML-Toolkits/python3-saml/issues/416

So closing this one.

P.S This error was raised because you did not provided a base64encoded valid SAMLResponse.
